primary:
  persistence:
    enabled: true
  initdb:
    scripts:
      01-init.sql: |
        create database if not exists postgres with owner postgres;
        create table if not exists users(user_id text, user_name text);
  postgresqlDatabase: postgres
  postgresqlUsername: postgres
  postgresqlPassword: password

global:
  postgresql:
    postgresqlDatabase: postgres
    postgresqlUsername: postgres
    postgresqlPassword: password
    image:
      debug: true
  pgpool:
    adminPassword: postgres
